#!/usr/bin/env python
import sys

from argparse import SUPPRESS, Action, ArgumentParser, RawDescriptionHelpFormatter

from jinja2.exceptions import TemplateNotFound

from config_render import ConfigRender, __version__, Parser, ConfigRenderException


CONFIG_HELP = """This help describdes how the config file should look like.

Example Config file:
# Special configuration which applies when -t and -o is specified
default:
  # Path to template
  # This is overridedid by -t option
  template_path: some_template.config
  # Enviroment template varible
  # if specified we firt try to use if not specified we fallback to
  # template_path
  template_path_var: SOME_TEMPLATE_PATH
  # This is overridedid by -o option
  output_file_path: something.cfg
  # if specified we firt try to use if not specified we fallback to
  # output_file_path
  output_file_path_var: SOME_OUTPUT_PATH
  # Load varibles from system environment
  # env_variables are superior to varibles
  env_variables:
    ip_adress: DJANGO_IP_ADDR
    hostname: DJANGO_HOSTNAME
    db_hostname: DB_HOSTNAME
  variables:
  # false, off is parsed as python False if you wan to use them as string
  # use "off"
    debug: off
    server_https: "on"
    db_type: postgresql
    ip_adress: 127.0.0.1 # fallback if DAJNGO_IP_ADDR does not exist


"""


class HelpConfig(Action):
    def __init__(self, option_strings, dest=SUPPRESS, default=SUPPRESS, help=None):
        super(HelpConfig, self).__init__(option_strings=option_strings, dest=dest, default=default,
                                         nargs=0, help=help)

    def __call__(self, parser, namespace, values, option_string=None):
        parser._print_message(CONFIG_HELP)
        parser.exit()

VERSION_TEXT = "%%(prog)s %s\n\nCopyright (C) 2016 Filip Dobrovolny\nLicense: MIT" % __version__
DESCRIPTION = "Render your files with Jinja2 templates."

parser = ArgumentParser(version=VERSION_TEXT, description=DESCRIPTION,
                        formatter_class=RawDescriptionHelpFormatter)
parser.register("action", "help_config", HelpConfig)
parser.add_argument("-ch", "--config-help", help="show config file help and exit",
                    action="help_config")
parser.add_argument("-n", "--name", metavar="config_name", type=str, default="default",
                    help="Name of configuration to be used.")
parser.add_argument("config", help="YAML config file")
parser.add_argument("-t", "--template_name", help="Template file", metavar="template")
parser.add_argument("-o", "--output_file", help="Output File", metavar="FILE")

args = parser.parse_args()
with open(args.config, "r") as f:
    conf = Parser(f).parse()

conf_render = ConfigRender()

try:
    configuration = conf[args.name].write(conf_render, template_name=args.template_name,
                                          output_file=args.output_file)
except (ConfigRenderException, TemplateNotFound) as e:
    sys.tracebacklimit = 0
    raise
